import matplotlib.pyplot as plt
import seaborn as sns
import os
import pandas as pd

def generate_charts(df, ticker, output_dir='outputs'):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    sns.set_theme(style="whitegrid")
    
    # 1. Closing Price Chart
    plt.figure(figsize=(12, 6))
    plt.plot(df.index, df['Close'], label='Close Price', color='blue')
    plt.title(f'{ticker} Closing Price')
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.legend()
    plt.savefig(f'{output_dir}/closing_price_chart.png')
    plt.close()
    
    # 2. Moving Averages Chart
    plt.figure(figsize=(12, 6))
    plt.plot(df.index, df['Close'], label='Close', alpha=0.5)
    plt.plot(df.index, df['SMA_20'], label='SMA 20')
    plt.plot(df.index, df['SMA_50'], label='SMA 50')
    plt.title(f'{ticker} Moving Averages')
    plt.legend()
    plt.savefig(f'{output_dir}/moving_average_chart.png')
    plt.close()
    
    # 3. Daily Returns
    plt.figure(figsize=(12, 6))
    sns.histplot(df['Daily_Return'].dropna(), bins=50, kde=True, color='green')
    plt.title(f'{ticker} Daily Returns Distribution')
    plt.savefig(f'{output_dir}/daily_returns_chart.png')
    plt.close()

def generate_markdown_report(df, backtest_results, ticker, report_dir='reports'):
    if not os.path.exists(report_dir):
        os.makedirs(report_dir)
        
    stats = df.describe()
    volatility = df['Volatility_30'].iloc[-1]
    
    report = f"""# Stock Analysis Report: {ticker}
Date generated: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}

## Summary Statistics
- **Highest Price**: {df['High'].max():.2f}
- **Lowest Price**: {df['Low'].min():.2f}
- **Recent Volatility (30d Ann.)**: {volatility:.2%}

## Performance Metrics
- **Count of Trading Days**: {len(df)}
- **Average Daily Return**: {df['Daily_Return'].mean():.4%}

## Backtest Results (SMA 20/50 Crossover)
- **Final Portfolio Value**: ${backtest_results['final_value']:.2f}
- **Total Return**: {backtest_results['total_return_pct']:.2f}%

---
*Generated by MarketMind Analytics Engine*
"""
    with open(f'{report_dir}/stock_analysis_report.md', 'w') as f:
        f.write(report)
    
    # Save volatility summary to CSV
    summary_df = pd.DataFrame({
        'Metric': ['Max High', 'Min Low', 'Current Volatility', 'Avg Return'],
        'Value': [df['High'].max(), df['Low'].min(), volatility, df['Daily_Return'].mean()]
    })
    summary_df.to_csv('outputs/volatility_summary.csv', index=False)
